config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end
  devise_scope :admin do
    post "admins/guest_sign_in", to: "admin/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "/about" => "homes#about"

  scope module: :user do
    get "/search" => "searches#index"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        collection do
          post "filter"
          get "filter"
        end
      end
    end

    resources :users, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "withdraw"
      end
      get "relationships/index" => "relationships#index"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      resource :blocks, only: [:create, :destroy]
      get "blockings" => "blocks#blockings", as: "blockings"
      get "blockers" => "blocks#blockers", as: "blockers"
    end
  end

  namespace :admin do
    get "/search" => "searches#index"
    resources :posts, only: [:index, :show, :update, :destroy] do
      member do
        patch "toggle_status"
        delete "comments/:comment_id", to: "comments#destroy_comment", as: :destroy_comment
      end
    end
    resources :users, only: [:index, :show, :update] do
      member do
        patch "user_ban"
      end
    end
    resources :comments, only: [:index, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @category = params[:category]
    @word = params[:word]
    if @category == "Post"
      if @word.present?
        @posts = Post.where(is_open: true).where("body LIKE?", "%#{@word}%")
      else
        @posts = []
        # =nil ではなく[]を使用。要素は無いが空の配列としてオブジェクトが存在。
      end
    elsif @category == "User"
      if @word.present?
        @users = User.where(is_active: true).where("name LIKE?", "%#{@word}%")
      else
        @users = []
      end
    else # @category == "Comment"
      if @word.present?
        @comments = Comment.where("comments.body LIKE?", "%#{@word}%")
      else
        @comments = []
      end
    end
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = params[:category]
    @word = params[:word]
    if @category == "Post"
      if @word.present?
        @posts = Post.where(is_open: true).where("body LIKE?", "%#{@word}%")
      else
        @posts = []
        # =nil ではなく[]を使用。要素は無いが空の配列としてオブジェクトが存在。
      end
    else # @category == "User"
      if @word.present?
        @users = User.where(is_active: true).where("name LIKE?", "%#{@word}%")
      else
        @users = []
      end
    end
  end
end

app/views/admin/searches/index.html.erb
<div class="container">
  <div class="row mt-3">
      <% if params[:word].blank? %>
        <div class="col-12 mt-3">
          ▽検索対象 を選択し、検索バーに入力してください。
        </div>
      <% else %>
        <div class="col-12 mt-3">
            <!--検索対象：Post-->
            <% if @category == "Post" %>
              <% if @posts.any? %>
                <div>Posts search for "<%= @word %>"</div>
                <table class="table mt-3">
                  <thead class="table-warning">
                    <tr>
                      <th>画像</th>
                      <th>本文</th>
                      <th>ユーザー名</th>
                      <th>コメント数</th>
                      <th>いいね数</th>
                      <th class="pb-1">
                        公開ステータス
                        <button type="button" class="btn btn-link pb-2 px-0" data-toggle='modal' data-target="#statusInfomation">
                          <i class="fa-solid fa-circle-info"></i>
                        </button>
                      </th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @posts.each do |post| %>
                      <tr>
                        <td class="td_vertical_align_middle">
                          <%= link_to post_path(post) do %>
                            <%= image_tag post.get_image, width: 50, height: 50 %>
                          <% end %>
                          </td>
                        <td class="td_vertical_align_middle">
                          <%= link_to post_path(post) do %>
                            <%= post.body %>
                          <% end %>
                        </td>
                        <td class="td_vertical_align_middle">
                          <%= link_to user_path(post.user_id) do %>
                            <%= post.user.name %>
                          <% end %>
                        </td>
                        <td class="td_vertical_align_middle">
                          <%= link_to post_path(post) do %>
                            <%= post.comments.count %>
                          <% end %>
                        </td>
                        <td class="td_vertical_align_middle">
                          <%= post.favorites.count %>
                        </td>
                        <td id="post-status-<%= post.id %>", class="td_vertical_align_middle">
                          <% unless is_guest_admin? %>
                            <%= link_to toggle_status_admin_post_path(post), method: :patch, remote: true, class: 'toggle-status-link', data: { post_id: post.id } do %>
                              <% if post.is_open %>
                                <span class="text-success">公開</span>
                              <% else %>
                                <span class="text-secondary">非公開</span>
                              <% end %>
                            <% end %>
                          <% else %>
                            <% if post.is_open %>
                              <span id="toggle-<%= post.id %>" class="text text-success">公開</span>
                            <% else %>
                              <span id="toggle-<%= post.id %>" class="text text-secondary">非公開</span>
                            <% end %>
                          <% end %>
                        </td>
                        <td class="td_vertical_align_middle">
                          <% unless is_guest_admin? %>
                            <%= link_to admin_post_path(post), method: :delete, data: {confirm: "完全に削除しますか？"}, class: "btn btn-sm btn-danger" do %>
                              削除
                            <% end %>
                          <% else %>
                            <div class="btn btn-sm btn-danger">削除</div>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              <% else %>
                <% if params[:word].present? %>
                  該当する投稿はありません。
                <% end %>
              <% end %>
            <!--検索対象：User-->
            <% elsif @category == "User" %>
              <% if @users.any? %>
                <div>Users search for "<%= @word %>"</div>
                <table class="table mt-3">
                  <thead class="table-success">
                    <tr>
                      <th>名前</th>
                      <th>投稿数</th>
                      <th>投稿（最大5枚表示）</th>
                      <th class="pb-1">
                        会員ステータス
                        <button type="button" class="btn btn-link pb-2 px-0" data-toggle='modal' data-target="#userStatusInfomation">
                          <i class="fa-solid fa-circle-info"></i>
                        </button>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <td class="td_vertical_align_middle">
                          <%= link_to user_path(user) do %>
                            <%= user.name %>
                          <% end %>
                          </td>
                        <td class="td_vertical_align_middle">
                          <%= user.posts.count %>
                        </td>
                        <td>
                          <% if user.posts.any? %>
                            <% user.posts.limit(10).each do |post| %>
                              <%= link_to admin_post_path(post) do %>
                                <%= image_tag post.get_image, width: 50, height: 50 %>
                              <% end %>
                            <% end %>
                          <% else %>
                            <div class="py-2">
                              投稿はありません。
                            </div>
                          <% end %>
                        </td>
                        <td id="user-status-<%= user.id %>", class="td_vertical_align_middle">
                          <% unless is_guest_admin? %>
                            <%= link_to user_ban_admin_user_path(user), method: :patch, remote: true, class: 'user-ban-link', data: { user_id: user.id } do %>
                              <% if user.is_active %>
                                <span class="text-success">有効</span>
                              <% else %>
                                <span class="text-secondary">退会済み</span>
                              <% end %>
                            <% end %>
                          <% else %>
                            <% if user.is_active %>
                              <span class="text-success">有効</span>
                            <% else %>
                              <span class="text-secondary">退会済み</span>
                            <% end %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <% else %>
                  <% if params[:word].present? %>
                    該当するユーザーはいません。
                  <% end %>
                <% end %>
              <!--検索対象：Comment-->
              <% else %>
                <% if @comments.any? %>
                  <div>Comments search for "<%= @word %>"</div>
                  <table class="table mt-3">
                    <thead class="table-light">
                      <tr>
                        <th>コメント</th>
                        <th></th>
                        <th>立場</th>
                        <th>Post</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @comments.each do |comment| %>
                        <tr>
                          <td class="td_vertical_align_middle">
                            <%= comment.body %>
                          </td>
                          <td class="td_vertical_align_middle">
                            by
                            <%= link_to admin_user_path(comment.user) do %>
                              <%= comment.user.name %>
                            <% end %>
                          </td>
                          <td class="td_vertical_align_middle">
                            <% case comment.stance %>
                            <% when 'agree' %>
                              <span class='text-success'><%= comment.stance_i18n %></span>
                            <% when 'neutral' %>
                              <span class='text-secondary'><%= comment.stance_i18n %></span>
                            <% when 'disagree' %>
                              <span class='text-danger'><%= comment.stance_i18n %></span>
                            <% end %>
                          </td>
                          <td>
                            <%= link_to admin_post_path(comment.post) do %>
                              <%= image_tag comment.post.get_image, width: 50, height: 50 %>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                <% else %>
                  <% if params[:word].present? %>
                    該当するコメントはありません。
                  <% end %>
                <% end %>
              <% end %>
            
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal" id="statusInfomation" tabindex="-1" role="dialog" aria-labelledby="statusInfomationTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="statusInfomation">公開ステータスについて</h5>
      </div>
      <div class="modal-body">
        公開/非公開を変更できます。<br/>
        文字をクリックしてください。<br/>
        ※guestは変更できません。<br/>
      </div>
      <div class="mordal-footer mb-3">
        <%= link_to 'OK', admin_posts_path, class:"btn btn-success px-5" %>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="userStatusInfomation" tabindex="-1" role="dialog" aria-labelledby="userStatusInfomationTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="userStatusInfomation">会員ステータスについて</h5>
      </div>
      <div class="modal-body">
        有効/退会済みを変更できます。<br/>
        文字をクリックしてください。<br/>
        ※guestは変更できません。<br/>
      </div>
      <div class="mordal-footer mb-3">
        <%= link_to 'OK', admin_users_path, class:"btn btn-success px-5" %>
      </div>
    </div>
  </div>
</div>