config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end
  devise_scope :admin do
    post "admins/guest_sign_in", to: "admin/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "/about" => "homes#about"

  scope module: :user do
    get "/search" => "searches#index"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        collection do
          post "filter"
          get "filter"
        end
      end
    end

    resources :users, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "withdraw"
      end
      get "relationships/index" => "relationships#index"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      resource :blocks, only: [:create, :destroy]
      get "blockings" => "blocks#blockings", as: "blockings"
      get "blockers" => "blocks#blockers", as: "blockers"
    end
  end

  namespace :admin do
    get "/search" => "searches#index"
    resources :posts, only: [:index, :show, :update, :destroy] do
      member do
        patch "toggle_status"
        delete "comments/:comment_id", to: "comments#destroy_comment", as: :destroy_comment
      end
    end
    resources :users, only: [:index, :show, :update] do
      member do
        patch "user_ban"
      end
    end
    resources :comments, only: [:index, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :hues, dependent: :destroy
  has_one_attached :image

  enum color: { red: 0, orange: 1, yellow: 2, green: 3, blue: 4, purple: 5, monochrome: 6, other: 7 }

  validates :body, presence: true, length: { maximum: 100 }
  validates :color, presence: true
  validate :image_type

  validate :check_consecutive_characters

  def get_image
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [200, 200]).processed
  end

  # いいねされているかどうかを確認するメソッドを定義。ログインしていないときは影響しない。
  def favorited_by?(user)
    user.present? && favorites.where(user_id: user.id).exists?
  end

  private
    def image_type
      if !image.blob
        errors.add(:image, "をアップロードしてください")
      elsif !image.blob.content_type.in?(%("image/jpeg image/png"))
        errors.add(:image, "はJPEGまたはPNG形式を選択してアップロードしてください")
      end
    end
  
    def check_consecutive_characters
      if body.match?(/(.)\1{3,}/)
        errors.add(:body, "に同じ文字が4文字以上連続して使用されています。")
      end
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.all

    case params[:sort_by]
    when "newest"
      @posts = @posts.order(created_at: :desc)
    when "oldest"
      @posts = @posts.order(created_at: :asc)
    when "comments"
      @posts = @posts.left_outer_joins(:comments).group(:id).order("COUNT(comments.id) DESC")
    else
      @posts = @posts.order(created_at: :desc)
    end
  end

  def toggle_status
    @post = Post.find(params[:id])
    # 公開←→非公開
    @post.update(is_open: !@post.is_open)

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :is_matching_login_user, only: [:edit, :update]

  include WordFilter

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # NGワードあれば変換
    ng_words = load_ng_words("#{Rails.root}/ng_words.txt")
    @post.body = filter_ng_words(params[:post][:body].downcase, ng_words)

    unless post_params[:image].present?
      flash.now[:alert] = "画像をアップロードしてください。"
      return render :new
    end

    @post.user_id = current_user.id
    # API用の変換
    base64_image = Vision.get_base64_image(post_params[:image])
    # vision APIを実装するためtagsに関する定義。Tagモデルは多の関係。
    tags = Vision.get_image_data(base64_image)
    # vision APIのimage_properties用の記述を追加。Hueモデルは多の関係。
    hues = Vision.analyze_image(base64_image)
    if @post.save
      # Tag用の指示
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      # Hue解析用の指示
      @post.hues.create(hues)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    unless @post.present?
      redirect_to posts_path, alert: "その投稿は表示できません。"
      return
    end
    # 非公開の場合、作成者以外は表示しない。
    unless @post.user == current_user
      @posts = Post.where(is_open: true)
    end
    @comments = @post.comments
    if user_signed_in?
      @comment = current_user.comments.new
    else
      @comment = Comment.new
    end
    
    @filter = params[:filter]
    case @filter
    # where メソッドには SQL の条件を文字列で渡す必要がある。@comment.score
    when "positive"
      @comments = @post.comments.where("score > ?", 0.1)
    when "negative"
      @comments = @post.comments.where("score < ?", 0)
    else
      @comments = @post.comments
    end
  end

  def index
    # 公開のもののみ
    @posts = Post.where(is_open: true)
    
    # 色タグでの分類をenumで設定した数字で行う。
    if params[:color].present?
      if params[:color] == "7"
        @posts = Post.all
      else
        @posts = Post.where(color: params[:color])
      end
    else # リロードして非選択が生じた場合用
      @posts = Post.all
    end

    if user_signed_in?
      blocked_user_ids = current_user.blockings.pluck(:id)
      # ブロックしているユーザーIDsを　　　　取得しない
      @posts = @posts.where.not(user_id: blocked_user_ids)
    end

    case params[:sort_by]
    when "newest"
      @posts = @posts.order(created_at: :desc)
    when "oldest"
      @posts = @posts.order(created_at: :asc)
    when "favorites"
      @posts = @posts.left_outer_joins(:favorites).group(:id).order("COUNT(favorites.id) DESC")
    when "comments"
      @posts = @posts.left_outer_joins(:comments).group(:id).order("COUNT(comments.id) DESC")
    else
      @posts = @posts.order(created_at: :desc)
    end
    # .joinsのみではいいね、コメント数が０のものを取得できないため、left_outer_joins/左外部結合 を使用。
    # 最後に@postsに対してページネーションを実行。
    # １ページあたりの表示数は、config/initializers/kaminari_config.rbに設定していたが、変更容易のためこちらへ。
    @posts = @posts.page(params[:page]).per(12)
  end

  def edit
    # :is_matching_login_user
  end

  def update
    # :is_matching_login_user
    @post.user_id = current_user.id
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :image, :body, :color, :is_open)
    end

    def is_matching_login_user
      @post = Post.find(params[:id])
      unless @post.user == current_user
        redirect_to posts_path
      end
    end
end

app/views/admin/posts/index.html.erb
投稿一覧ページ
<div class="row my-3">
  <div class="col-xl-6 col-xs">
    <%= link_to "新しい順", admin_posts_path(sort_by: 'newest'), class: "no-underline" %>&nbsp;|&nbsp;
    <%= link_to "古い順", admin_posts_path(sort_by: 'oldest'), class: "no-underline" %>&nbsp;|&nbsp;
    <%= link_to "コメント順", admin_posts_path(sort_by: 'comments'), class: "no-underline" %>
  </div>
</div>
<% if @posts.any? %>
  <table class="table mt-3">
    
    <thead class="table-warning">
      <tr>
        <th>画像</th>
        <th>本文</th>
        <th>ユーザー名</th>
        <th>コメント数</th>
        <th>いいね数</th>
        <th class="pb-1">
          公開ステータス
          <button type="button" class="btn btn-link pb-2 px-0" data-toggle='modal' data-target="#statusInfomation">
            <i class="fa-solid fa-circle-info"></i>
          </button>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= link_to admin_post_path(post) do %>
              <%= image_tag post.get_image, width: 50, height: 50 %>
            <% end %>
          </td>
          <td class="td_vertical_align_middle">
            <%= link_to admin_post_path(post) do %>
              <%= post.body %>
            <% end %>
          </td>
          <td class="td_vertical_align_middle">
            <%= link_to admin_user_path(post.user_id) do %>
              <%= post.user.name %>
            <% end %>
          </td>
          <td class="td_vertical_align_middle">
            <%= post.comments.count %>
          </td>
          <td class="td_vertical_align_middle">
            <%= post.favorites.count %>
          </td>
          <td id="post-status-<%= post.id %>", class="td_vertical_align_middle">
            <% unless is_guest_admin? %>
              <%= link_to toggle_status_admin_post_path(post), method: :patch, remote: true, class: 'toggle-status-link', data: { post_id: post.id } do %>
                <% if post.is_open %>
                  <span class="text-success">公開</span>
                <% else %>
                  <span class="text-secondary">非公開</span>
                <% end %>
              <% end %>
            <% else %>
              <% if post.is_open %>
                <span id="toggle-<%= post.id %>" class="text text-success">公開</span>
              <% else %>
                <span id="toggle-<%= post.id %>" class="text text-secondary">非公開</span>
              <% end %>
            <% end %>
          </td>
          <td class="td_vertical_align_middle">
            <% unless is_guest_admin? %>
              <%= link_to admin_post_path(post), method: :delete, data: {confirm: "完全に削除しますか？"}, class: "btn btn-sm btn-danger" do %>
                削除
              <% end %>
            <% else %>
              <div class="btn btn-sm btn-danger">削除</div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  投稿はありません。
<% end %>

<div class="modal" id="statusInfomation" tabindex="-1" role="dialog" aria-labelledby="statusInfomationTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="statusInfomation">公開ステータスについて</h5>
      </div>
      <div class="modal-body">
        公開/非公開を変更できます。<br/>
        文字をクリックしてください。<br/>
        ※guestは変更できません。<br/>
      </div>
      <div class="mordal-footer mb-3">
        <%= link_to 'OK', admin_posts_path, class:"btn btn-success px-5" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
投稿詳細ページ
<div class="container">
  <div class="row d-flex justify-content-center">
    <!--画面左側の要素-->
    <div class="col-lg-4">
      <div class="flame ml-lg-5 text-center mb-4 mb-md-0">
        <div class="image m-3">
          <%= image_tag @post.image.variant(resize_to_fill: [200, 200]).processed, size: "200x200" %>
        </div>
        <div class="row d-flex justify-content-end mr-1">
          <div classs="badge bg-primary text-wrap", style="width: 12em;">
            <%= link_to admin_user_path(@post.user) do %>
              <%= @post.user.name %>
            <% end %>
          </div>
        <div class="mr-4">
          <i class="fa-regular fa-heart"></i>
          <%= @post.favorites.count %> いいね
        </div>
        </div>
      </div>
      <div id="post-status-<%= @post.id %>", class="td_vertical_align_middle mt-3">
        <% unless is_guest_admin? %>
          <%= link_to toggle_status_admin_post_path(@post), method: :patch, remote: true, class: 'toggle-status-link', data: { post_id: @post.id } do %>
            <% if @post.is_open %>
              <span class="text-success">公開</span>
            <% else %>
              <span class="text-secondary">非公開</span>
            <% end %>
          <% end %>
        <% else %>
          <% if @post.is_open %>
            <span class="text-success">公開</span>
          <% else %>
            <span class="text-secondary">非公開</span>
          <% end %>
        <% end %>
      </div>
      <div class="td_vertical_align_middle mt-2">
        <% unless is_guest_admin? %>
          <%= link_to admin_post_path(@post), method: :delete, data: {confirm: "完全に削除しますか？"}, class: "btn btn-sm btn-danger" do %>
            投稿削除
          <% end %>
        <% else %>
          <div class="btn btn-sm btn-danger">投稿削除</div>
        <% end %>
      </div>
    </div>
    <!--画面右側の要素-->
    <div class="col-lg-6 offset-lg-1 mt-4">
      <div class="row ml-3 mb-3">
        本文：<%= @post.body %>
      </div>

      <% if @post.comments.any? %>
        <% @post.comments.each do |comment| %>
          <% comment_stance = case comment.stance
                              when 'agree'
                                "comment-agree"
                              when 'neutral'
                                "comment-neutral"
                              when 'disagree'
                                "comment-disagree"
                              end %>
          <div class="row mt-2">
            <div class="col-md-6 mb-2">
              <div class="<%= comment_stance %>">
                <%= comment.body %>
              </div>
            </div>
            <div class="col-3 mb-2">
              <%= comment.user.name %>
            </div>
            <div class="col-2 mb-2">
              <%= link_to '削除', destroy_comment_admin_post_path(@post, comment), method: :delete, class:"btn btn-sm btn-danger" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col my-5">
          まだコメントがありません。
        </div>
      <% end %>
  </div>
</div>

app/views/admin/posts/toggle_status.js.erb
<!--再度宣言していくため、varを使う-->
var postId = <%= @post.id %>;
var statusCell = document.getElementById("post-status-" + postId);
var isOpen = <%= @post.is_open %>;

if (<%= @post.is_open %>) {
  statusCell.innerHTML = `
    <%= link_to toggle_status_admin_post_path(@post), method: :patch, remote: true, data: { turbolinks: false }, class: 'toggle-status-link', data: { post_id: @post.id } do %>
      <span class="text-success">公開</span>
    <% end %>
  `;
} else {
  statusCell.innerHTML = `
    <%= link_to toggle_status_admin_post_path(@post), method: :patch, remote: true, data: { turbolinks: false }, class: 'toggle-status-link', data: { post_id: @post.id } do %>
      <span class="text-secondary">非公開</span>
    <% end %>
  `;
}