config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end
  devise_scope :admin do
    post "admins/guest_sign_in", to: "admin/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "/about" => "homes#about"

  scope module: :user do
    get "/search" => "searches#index"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        collection do
          post "filter"
          get "filter"
        end
      end
    end

    resources :users, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "withdraw"
      end
      get "relationships/index" => "relationships#index"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      resource :blocks, only: [:create, :destroy]
      get "blockings" => "blocks#blockings", as: "blockings"
      get "blockers" => "blocks#blockers", as: "blockers"
    end
  end

  namespace :admin do
    get "/search" => "searches#index"
    resources :posts, only: [:index, :show, :update, :destroy] do
      member do
        patch "toggle_status"
        delete "comments/:comment_id", to: "comments#destroy_comment", as: :destroy_comment
      end
    end
    resources :users, only: [:index, :show, :update] do
      member do
        patch "user_ban"
      end
    end
    resources :comments, only: [:index, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
    
    case params[:sort_by]
    when "ids"
      @users = @users.order("id")
    when "names"
      @suers = @users.order("name")
    when "posts"
      @users = @users.left_joins(:posts).select("users.*, COUNT(posts.id) as posts_count").group(:id).order("posts_count DESC")
      # lest_joins 投稿数０でも表示するために。select()各ユーザーの投稿数をカウント。users.id, users.name...すべて＊
    else
      @users = @users.order(created_at: :desc)
    end
  end

  def user_ban
    @user = User.find(params[:id])
    # 有効←→退会済み
    @user.update(is_active: !@user.is_active)

    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/controllers/user/blocks_controller.rb
class User::BlocksController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.block(@user)
    if current_user.following?(@user)
      current_user.unfollow(@user)
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unblock(@user)
  end

  def blockings
    user = User.find(params[:user_id])
    @users = user.blockings
  end

  def blockers
    user = User.find(params[:user_id])
    @users = user.blockers
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  include WordFilter

  def create
    @post = Post.find(params[:post_id])
    unless @post.user.blocking?(current_user)
      ng_words = load_ng_words("#{Rails.root}/ng_words.txt")
      @comment = current_user.comments.new(comment_params)
      # API language導入。
      @comment.score = Language.get_data(comment_params[:body])
      
      @comment.body = filter_ng_words(params[:comment][:body].downcase, ng_words)
      if @comment.save
        redirect_back(fallback_location: post_path(params[:post_id]))
      else
        flash[:alert] = @comment.errors.full_messages.join(" / ")
        redirect_back(fallback_location: post_path(params[:post_id]))
      end
    else
      flash[:error] = "この投稿にはコメントできなくなりました。"
      redirect_back(fallback_location: post_path(params[:post_id]))
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id], post_id: params[:post_id])
    @comment.destroy
    redirect_to post_path(params[:post_id])
  end

  def filter
    # filterアクションとして選択されたスタンスごとに表示
    @post = Post.find(params[:post_id])
    @comment = Comment.new

    # フィルター条件を保持
    @selected_stance = params[:comment][:stance] if params[:comment].present?

    if params[:comment].present? && params[:comment][:stance].present? && params[:comment][:stance] != "clear"
      @comments = @post.comments.where(stance: params[:comment][:stance])
    else
      @comments = @post.comments
    end
    render "user/posts/show"
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :stance, :post_id)
    end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    if current_user.present?
      favorite = @post.favorites.new(user_id: current_user.id)
      favorite.save
      # redirect_to request.referer
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = @post.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :is_matching_login_user, only: [:edit, :update]

  include WordFilter

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # NGワードあれば変換
    ng_words = load_ng_words("#{Rails.root}/ng_words.txt")
    @post.body = filter_ng_words(params[:post][:body].downcase, ng_words)

    unless post_params[:image].present?
      flash.now[:alert] = "画像をアップロードしてください。"
      return render :new
    end

    @post.user_id = current_user.id
    # API用の変換
    base64_image = Vision.get_base64_image(post_params[:image])
    # vision APIを実装するためtagsに関する定義。Tagモデルは多の関係。
    tags = Vision.get_image_data(base64_image)
    # vision APIのimage_properties用の記述を追加。Hueモデルは多の関係。
    hues = Vision.analyze_image(base64_image)
    if @post.save
      # Tag用の指示
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      # Hue解析用の指示
      @post.hues.create(hues)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    unless @post.present?
      redirect_to posts_path, alert: "その投稿は表示できません。"
      return
    end
    # 非公開の場合、作成者以外は表示しない。
    unless @post.user == current_user
      @posts = Post.where(is_open: true)
    end
    @comments = @post.comments
    if user_signed_in?
      @comment = current_user.comments.new
    else
      @comment = Comment.new
    end
    
    @filter = params[:filter]
    case @filter
    # where メソッドには SQL の条件を文字列で渡す必要がある。@comment.score
    when "positive"
      @comments = @post.comments.where("score > ?", 0.1)
    when "negative"
      @comments = @post.comments.where("score < ?", 0)
    else
      @comments = @post.comments
    end
  end

  def index
    # 公開のもののみ
    @posts = Post.where(is_open: true)
    
    # 色タグでの分類をenumで設定した数字で行う。
    if params[:color].present?
      if params[:color] == "7"
        @posts = Post.all
      else
        @posts = Post.where(color: params[:color])
      end
    else # リロードして非選択が生じた場合用
      @posts = Post.all
    end

    if user_signed_in?
      blocked_user_ids = current_user.blockings.pluck(:id)
      # ブロックしているユーザーIDsを　　　　取得しない
      @posts = @posts.where.not(user_id: blocked_user_ids)
    end

    case params[:sort_by]
    when "newest"
      @posts = @posts.order(created_at: :desc)
    when "oldest"
      @posts = @posts.order(created_at: :asc)
    when "favorites"
      @posts = @posts.left_outer_joins(:favorites).group(:id).order("COUNT(favorites.id) DESC")
    when "comments"
      @posts = @posts.left_outer_joins(:comments).group(:id).order("COUNT(comments.id) DESC")
    else
      @posts = @posts.order(created_at: :desc)
    end
    # .joinsのみではいいね、コメント数が０のものを取得できないため、left_outer_joins/左外部結合 を使用。
    # 最後に@postsに対してページネーションを実行。
    # １ページあたりの表示数は、config/initializers/kaminari_config.rbに設定していたが、変更容易のためこちらへ。
    @posts = @posts.page(params[:page]).per(12)
  end

  def edit
    # :is_matching_login_user
  end

  def update
    # :is_matching_login_user
    @post.user_id = current_user.id
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :image, :body, :color, :is_open)
    end

    def is_matching_login_user
      @post = Post.find(params[:id])
      unless @post.user == current_user
        redirect_to posts_path
      end
    end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?
  include WordFilter
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    ng_words = load_ng_words("#{Rails.root}/ng_words.txt")

    # ユーザー名を大文字から小文字に変換してNGワードのチェックを行う
    downcased_name = params[:user][:name].downcase
    filtered_name = filter_ng_words(downcased_name, ng_words)

    # フィルター後の名前が変わっているかチェック
    if filtered_name != downcased_name
      flash[:alert] = "別の名前を使用してください。"
      redirect_to new_user_registration_path
      return
    end
    # NGワードが含まれていない場合は、元のユーザー名（大文字の場合はそのまま）に戻し、通常処理を実行
    params[:user][:name] = params[:user][:name]
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    posts_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    unless current_user.blocking?(@user)
      current_user.follow(@user)
      # redirect_to request.referer
    else
      redirect_to user_path(@user), notice: "フォローするにはブロックの解除が必要です。"
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
    # redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = params[:category]
    @word = params[:word]
    if @category == "Post"
      if @word.present?
        @posts = Post.where(is_open: true).where("body LIKE?", "%#{@word}%")
      else
        @posts = []
        # =nil ではなく[]を使用。要素は無いが空の配列としてオブジェクトが存在。
      end
    else # @category == "User"
      if @word.present?
        @users = User.where(is_active: true).where("name LIKE?", "%#{@word}%")
      else
        @users = []
      end
    end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def after_sign_in_path_for(resource)
    posts_path
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました。"
  end

  private
    def user_state
      # [userのログインフォームに入力したemailの値]を用いて一致するemailカラムを持つuserを１件特定する。
      user = User.find_by(email: params[:user][:email])
      # もしuser=nilがtrueなら（存在しなければ）retuen（user_stateメソッド終了！）。falseなら次の行へ進む。
      return if user.nil?
      # [userのログインフォームに入力したpasswordの値]と先ほど特定したuserのpasswordが一致しないのであれば、retuen。trueなら次の行へ進む。
      return unless user.valid_password?(params[:user][:password])
      # ここでようやくis_activeがtrueかfalseかを条件分岐する。falseのときに実行したいことを
      unless user.is_active
        flash[:danger] = "退会済のアカウントです。新規登録をお願いします。"
        redirect_to new_user_session_path
      end
    end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :check_authorization, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    # 自分の投稿を表示する状態がdefault
    @filter = params[:filter] || "own"

    case @filter
    when "timeline"
      @posts = Post.where(user_id: @user.followings).order(created_at: :desc)
    when "own"
      @posts = @user.posts
    when "favorites"
      @posts = current_user.favorite_posts
    when "all"
      # params[:id]のユーザー（current_user）が投稿したpost。もしくは、current_userがいいねしたpost_idから特定したPost。を@postとする。
      @posts = Post.where(user: @user).or(Post.where(id: current_user.favorite_posts.pluck(:id)))
    else
      @posts = @user.posts
    end
  end

  def edit
    # check_authorization
  end

  def update
    # check_authorization
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def withdraw
    @user = current_user
    @user.update(is_active: false)
    reset_session
    redirect_to new_user_registration_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def check_authorization
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end

    def ensure_guest_user
      @user = User.find(params[:id])
      if @user.guest_user?
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end
end

app/helpers/user/blocks_helper.rb
module User::BlocksHelper
end

app/views/admin/users/index.html.erb
ユーザー一覧ページ
<div class="row my-3">
  <div class="col-xl-6 col-xs">
    <%= link_to "id順", admin_users_path(sort_by: 'ids'), class: "no-underline" %>&nbsp;|&nbsp;
    <%= link_to "名前順", admin_users_path(sort_by: 'names'), class: "no-underline" %>&nbsp;|&nbsp;
    <%= link_to "投稿数順", admin_users_path(sort_by: 'posts'), class: "no-underline" %>
  </div>
</div>
<% if @users.any? %>
  <table class="table mt-3">
    <thead class="table-success">
      <tr>
        <th>名前</th>
        <th>投稿数</th>
        <th>投稿（最大10枚表示）</th>
        <th class="pb-1">
          会員ステータス
          <button type="button" class="btn btn-link pb-2 px-0" data-toggle='modal' data-target="#userStatusInfomation">
            <i class="fa-solid fa-circle-info"></i>
          </button>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="td_vertical_align_middle">
            <%= link_to admin_user_path(user) do %>
              <%= user.name %>
            <% end %>
            </td>
          <td class="td_vertical_align_middle"><%= user.posts.count %></td>
          <td>
            <% if user.posts.any? %>
              <% user.posts.limit(10).each do |post| %>
                <%= link_to admin_post_path(post) do %>
                  <%= image_tag post.get_image, width: 50, height: 50 %>
                <% end %>
              <% end %>
            <% else %>
              <div class="py-2">
                投稿はありません。
              </div>
            <% end %>
          </td>
          <td id="user-status-<%= user.id %>", class="td_vertical_align_middle">
            <% unless is_guest_admin? %>
              <%= link_to user_ban_admin_user_path(user), method: :patch, remote: true, class: 'user-ban-link', data: { user_id: user.id } do %>
                <% if user.is_active %>
                  <span class="text-success">有効</span>
                <% else %>
                  <span class="text-secondary">退会済み</span>
                <% end %>
              <% end %>
            <% else %>
              <% if user.is_active %>
                <span class="text-success">有効</span>
              <% else %>
                <span class="text-secondary">退会済み</span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <% if params[:word].present? %>
    ユーザーはいません。
  <% end %>
<% end %>

<div class="modal" id="userStatusInfomation" tabindex="-1" role="dialog" aria-labelledby="userStatusInfomationTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="userStatusInfomation">会員ステータスについて</h5>
      </div>
      <div class="modal-body">
        有効/退会済みを変更できます。<br/>
        文字をクリックしてください。<br/>
        ※guestは変更できません。<br/>
      </div>
      <div class="mordal-footer mb-3">
        <%= link_to 'OK', admin_users_path, class:"btn btn-success px-5" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
ユーザー詳細ページ
<div class="container px-0">
  <div class="row d-flex justify-content-start mt-3 ">
    <div class="col-4">
      ユーザー名：<strong><%= @user.name %></strong>
    </div>
    <div id="user-status-<%= @user.id %>", class="col-3">
      <% unless current_admin == Admin.find(2) %>
        <%= link_to user_ban_admin_user_path(@user), method: :patch, remote: true, class: 'user-ban-link', data: { user_id: @user.id } do %>
          <% if @user.is_active %>
            <span class="text-success">有効</span>
          <% else %>
            <span class="text-secondary">退会済み</span>
          <% end %>
        <% end %>
      <% else %>
        <% if @user.is_active %>
          <span class="text-success">有効</span>
        <% else %>
          <span class="text-secondary">退会済み</span>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @posts.any? %>
    <table class="table mt-3">
      <thead class="table table-warning">
        <tr>
          <th>画像</th>
          <th>本文</th>
          <th>コメント数</th>
          <th>いいね数</th>
          <th class="pb-1">
            公開ステータス
            <button type="button" class="btn btn-link pb-2 px-0" data-toggle='modal' data-target="#poststatusInfomation">
              <i class="fa-solid fa-circle-info"></i>
            </button>
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td>
              <%= link_to admin_post_path(post) do %>
                <%= image_tag post.get_image, width: 50, height: 50 %>
              <% end %>
              </td>
            <td class="td_vertical_align_middle">
              <%= link_to admin_post_path(post) do %>
                <%= post.body %>
              <% end %>
            </td>
            <td class="td_vertical_align_middle">
              <%= post.comments.count %>
            </td>
            <td class="td_vertical_align_middle">
              <%= post.favorites.count %>
            </td>
            <td id="post-status-<%= post.id %>", class="td_vertical_align_middle">
              <% unless is_guest_admin? %>
                <%= link_to toggle_status_admin_post_path(post), method: :patch, remote: true, class: 'toggle-status-link', data: { post_id: post.id } do %>
                  <% if post.is_open %>
                    <span class="text-success">公開</span>
                  <% else %>
                    <span class="text-secondary">非公開</span>
                  <% end %>
                <% end %>
              <% else %>
                <% if post.is_open %>
                  <span class="text-success">公開</span>
                <% else %>
                  <span class="text-secondary">非公開</span>
                <% end %>
              <% end %>
            </td>
            <td class="td_vertical_align_middle">
              <% unless is_guest_admin? %>
                <%= link_to admin_post_path(post), method: :delete, data: {confirm: "完全に削除しますか？"}, class: "btn btn-sm btn-danger" do %>
                  削除
                <% end %>
              <% else %>
                <div class="btn btn-sm btn-danger">削除</div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    投稿はありません。
  <% end %>
</div>

<div class="modal" id="poststatusInfomation" tabindex="-1" role="dialog" aria-labelledby="poststatusInfomationTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="poststatusInfomation">公開ステータスについて</h5>
      </div>
      <div class="modal-body">
        公開/非公開を変更できます。<br/>
        文字をクリックしてください。<br/>
        ※guestは変更できません。<br/>
      </div>
      <div class="mordal-footer mb-3">
        <%= link_to 'OK', admin_user_path(@user), class:"btn btn-success px-5" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/user_ban.js.erb
var userId = <%= @user.id %>;
var statusCell = document.getElementById("user-status-" + userId);
var isOpen = <%= @user.is_active %>;

if (<%= @user.is_active %>) {
  statusCell.innerHTML = `
    <%= link_to user_ban_admin_user_path(@user), method: :patch, remote: true, class: 'user-ban-link', data: { user_id: @user.id } do %>
      <span class="text-success">有効</span>
    <% end %>
  `;
  } else {
  statusCell.innerHTML = `
    <%= link_to user_ban_admin_user_path(@user), method: :patch, remote: true, class: 'user-ban-link', data: { user_id: @user.id } do %>
      <span class="text-secondary">退会済み</span>
    <% end %>
  `;
}