config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end
  devise_scope :admin do
    post "admins/guest_sign_in", to: "admin/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "/about" => "homes#about"

  scope module: :user do
    get "/search" => "searches#index"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        collection do
          post "filter"
          get "filter"
        end
      end
    end

    resources :users, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "withdraw"
      end
      get "relationships/index" => "relationships#index"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      resource :blocks, only: [:create, :destroy]
      get "blockings" => "blocks#blockings", as: "blockings"
      get "blockers" => "blocks#blockers", as: "blockers"
    end
  end

  namespace :admin do
    get "/search" => "searches#index"
    resources :posts, only: [:index, :show, :update, :destroy] do
      member do
        patch "toggle_status"
        delete "comments/:comment_id", to: "comments#destroy_comment", as: :destroy_comment
      end
    end
    resources :users, only: [:index, :show, :update] do
      member do
        patch "user_ban"
      end
    end
    resources :comments, only: [:index, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_color_palette.html.erb
<div class="col-4">
  <div class="color-palette">
    <div class="color-row">
      <%= link_to posts_path(color: '0') do %>
        <div class="square red"></div>
      <% end %>
      <%= link_to posts_path(color: '1') do %>
        <div class="square orange"></div>
      <% end %>
      <%= link_to posts_path(color: '2') do %>
        <div class="square yellow"></div>
      <% end %>
      <%= link_to posts_path(color: '3') do %>
        <div class="square green"></div>
      <% end %>
    </div>
    <div class="color-row">
      <%= link_to posts_path(color: '4') do %>
        <div class="square blue"></div>
      <% end %>
      <%= link_to posts_path(color: '5') do %>
        <div class="square purple"></div>
      <% end %>
      <%= link_to posts_path(color: '6') do %>
        <div class="square monochrome"></div>
      <% end %>
      <%= link_to posts_path(color: '7') do %>
        <div class="square other"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul class="list-unstyled" >
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div>
  <div class="row my-2 justify-content-center">
    <a class="no-underline" href="#" data-toggle="modal" data-target="#TermInfomation">
      利用規約
    </a>&emsp;&emsp;
    <a class="no-underline" href="#" data-toggle="modal" data-target="#PrivacyInfomation">
      プライバシーポリシー
    </a>
  </div>
  <div class="row justify-content-end mr-3">
    <span>Copyright © Infratop Inc. All Rights Reserved.</span>
  </div>
</div>

<div class="modal fade" id="TermInfomation" tabindex="-1" role="dialog" aria-labelledby="TermInfomationTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="TermInfomation"><strong>利用規約</strong></h5>
      </div>
      <div class="modal-body mb-3 px-4">
        <%= render "layouts/term" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success mr-4" data-dismiss="modal">同意する</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="PrivacyInfomation" tabindex="-1" role="dialog" aria-labelledby="PrivacyInfomationTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="PrivacyInfomation"><strong>プライバシーポリシー</strong></h5>
      </div>
      <div class="modal-body mb-3 px-4">
        <%= render "layouts/privacy" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success mr-4" data-dismiss="modal">同意する</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row header-content">
  <!--左端：Logoの表示について-->
  <% if current_page?(root_path) %>
    <div class="col-1 mx-3">
      <div class="row"></div>
      <div class="row">
        <% if admin_signed_in? %>
          <%= image_tag("admininfo.png", src: "/assets/images/admininfo.png", width: 100, hight: 100 ) %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="col-1 mx-3">
      <div class="row">
        <%= link_to root_path do %>
          <%= image_tag("logoA.png", src: "/assets/images/logoA.png", width: 100, hight: 100 ) %>
        <% end %>
      </div>
      <div class="row">
        <% if admin_signed_in? %>
          <%= image_tag("admininfo.png", src: "/assets/images/admininfo.png", width: 100, hight: 100 ) %>
        <% end %>
      </div>
    </div>
  <% end %>
  <!--中央：リンクの表示について-->
  <ul class="col-sm-7 col-xs-10 d-flex list-unstyled justify-content-center my-auto">
    <% if admin_signed_in? %>
      <div class="col d-flex align-items-center justify-content-center">
        <li class='mx-3'><%= link_to admin_posts_path, class: "no-underline" do %><strong>Post List</strong><% end %></li>
        <li class='mx-3'><%= link_to admin_users_path, class: "no-underline" do %><strong>User List</strong><% end %></li>
        <li class='mx-3'><%= link_to admin_comments_path, class: "no-underline" do %><strong>Comment List</strong><% end %></li>
        <li class='mx-3'><%= link_to destroy_admin_session_path, method: :delete, class: "no-underline" do %><strong>Log out</strong><% end %></li>
      </div>
    <% elsif user_signed_in? %>
      <div class="col d-flex align-items-center justify-content-center">
        <li class='mx-3'><%= link_to about_path, class: "no-underline" do %><strong>About</strong><% end %></li>
        <li class='mx-3'><%= link_to new_post_path, class: "no-underline" do %><strong>Post</strong>&nbsp;<i class="fa-solid fa-pen-to-square"></i><% end %></li>
        <li class='mx-3'><%= link_to user_path(current_user), class: "no-underline" do %><strong>My Page</strong><% end %></li>
        <li class='mx-3'><%= link_to destroy_user_session_path, method: :delete, class: "no-underline" do %><strong>Log out</strong><% end %></li>
      </div>
    <% else %>
      <div class="col d-flex align-items-center justify-content-center">
        <li class='mx-3'><%= link_to about_path, class: "no-underline" do %><strong>About</strong><% end %></li>
        <li class='mx-3'><%= link_to new_user_registration_path, class: "no-underline" do %><strong>Sign up</strong><% end %></li>
        <li class='mx-3'><%= link_to new_user_session_path, class: "no-underline" do %><strong>Log in</strong><% end %></li>
      </div>
    <% end %>
  </ul>
  <!--右端：カラーパレットの表示について-->
  <% unless current_page?(root_path) %>
    <div class="col-md-2 col-sm-12">
      <div class="row justify-content-center">
        <%= render 'layouts/color_palette' %>
      </div>
    </div>
  <% else %>
    <% if user_signed_in?%>
      <div class="col-md-2 col-sm-12 mx-5"></div>
    <% else %>
      <div class="col-md-2 col-sm-12 mx-5 my-auto">
        for admin
        <button type="button" class="btn btn-link pb-2 px-0" data-toggle='modal' data-target="#foradminInfomation">
          <i class="fa-solid fa-circle-info"></i>
        </button>
      </div>
    <% end %>
  <% end %>
</div>
<!--要件：ログイン時のみheader下部に検索フォームを表示-->
<% if user_signed_in? && !admin_signed_in? %>
  <div class="row mt-2 ml-4">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :category, options_for_select([['Post'],['User']]) %>
      <button type="submit" class="btn btn-sm btn-warning my-auto">
        <i class="fas fa-search"></i>
      </button>
    <% end %>
  </div>
<% elsif admin_signed_in? %>
  <div class="row mt-2 ml-4">
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :category, options_for_select([['Post'],['User'],['Comment']]) %>
      <button type="submit" class="btn btn-sm btn-warning my-auto">
        <i class="fas fa-search"></i>
      </button>
    <% end %>
  </div>
<% end %>
  <span class="notice"><%= notice %></span>
  <span><strong class="alert"><%= alert %></strong></span>

<div class="modal" id="foradminInfomation" tabindex="-1" role="dialog" aria-labelledby="foradminInfomationTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header pl-5">
        <h5 class="modal-title" id="foradminInfomation">adminログインについて</h5>
      </div>
      <div class="modal-body mb-3 px-4">
        <h4><strong>機能要件変更</strong></h4>
        セキュリティ面を配慮し、以下のように変更されました。<br/>
        ・ユーザー側の画面とは別に、管理者自身のログイン画面および管理者機能がある<br/>
        ・予めデータベースに登録したID/パスワードをもとにログインが可能である<br/></br>
        admin画面も見ていただける方は<br/>
        <strong>/admins/sign_in</strong> よりゲストアドミンでログインしてください。<br/>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_privacy.html.erb
本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，
ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。<br/>
<br/>
１．収集する情報<br/>
本サービスでは、以下の情報を収集します：ユーザー名、メールアドレス、投稿された画像<br/>
<br/>
２．情報の利用目的<br/>
収集した情報は、サービスの提供および改善、ユーザーサポート、運営のために使用します。<br/>
<br/>
３．情報の共有<br/>
ユーザーの同意なく第三者と情報を共有することはありません。<br/>
ただし、法的な要求や運営上必要がある場合を除きます。<br/>
<br/>
４．ユーザーの権利<br/>
ユーザーは、自分の情報にアクセスし、修正、削除をする権利があります。<br/>
<br/>
５．個人情報の利用停止<br/>
ユーザーの個人情報は、適用される法律や規制に基づき、必要に応じて利用停止することがあります。<br/>
<br/>
６．ポリシーの変更<br/>
本ポリシーは随時変更されることがあります。変更があった場合、サービス内で通知します。<br/>
<br/>
以上

app/views/layouts/_term.html.erb
本ウェブサイト上で提供するサービス（以下，「本サービス」といいます。）における利用条件を定めるものです。
利用者の皆さま（以下，「ユーザー」といいます。）には，本規約に従って本サービスをご利用いただきます。<br/>
<br/>
１．ユーザーの責任<br/>
ユーザーは、投稿内容や行動が法令や本規約に違反しないようにし、
他のユーザーや第三者に対しても尊重をもって行動する責任があります。<br/>
<br/>
２．ユーザーIDおよびパスワードの管理<br/>
ユーザーは、自身のユーザーIDおよびパスワードを適切に管理する責任があります。<br/>
ユーザーIDおよびパスワードは、他人に譲渡、貸与、共有することはできません。
ユーザーIDとパスワードの組み合わせが正しければ、その利用は登録ユーザー自身によるものとみなします。<br/>
ユーザーIDおよびパスワードが第三者によって使用されて生じた損害については、
製作者に故意または重大な過失がない限り、製作者は責任を負いません。<br/>
<br/>
３．禁止事項<br/>
次の行為は禁止します：違法なコンテンツの投稿、他者を誹謗中傷する行為、
差別や嫌がらせ、わいせつなコンテンツの公開、自殺を助長する情報の発信など。<br/>
<br/>
４．個人情報保護<br/>
個人情報はプライバシーポリシーに従って取り扱います。
ユーザーの同意なしに第三者と情報を共有することはありません。
ただし、法的要求や運営上の必要がある場合を除きます。<br/>
<br/>
５．免責事項<br/>
当サービスは、データの損失やサービスの中断に対して責任を負いません。
サービスの利用は自己責任で行ってください。<br/>
<br/>
６．変更について<br/>
利用規約は予告なく変更されることがあります。
変更があった場合は、サービス内で通知します。
ユーザーは定期的に規約を確認する責任があります。<br/>
<br/>
以上

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Own Palette</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/18d078742a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>